package com.example.incidentapi.common.message;
/**
 * Message Id
 */
public class MessageKeys {
    /** e.ex.fw.5001=Resource not found. */
    public static final String E_EX_FW_5001 = "e.ex.fw.5001";
    /** e.ex.fw.6001=Request method not supported. */
    public static final String E_EX_FW_6001 = "e.ex.fw.6001";
    /** e.ex.fw.6002=Specified representation format not supported. */
    public static final String E_EX_FW_6002 = "e.ex.fw.6002";
    /** e.ex.fw.6003=Specified media type in the request body not supported. */
    public static final String E_EX_FW_6003 = "e.ex.fw.6003";
    /** e.ex.fw.7001=Validation error occurred on item in the request body. */
    public static final String E_EX_FW_7001 = "e.ex.fw.7001";
    /** e.ex.fw.7002=Validation error occurred on item in the request parameters. */
    public static final String E_EX_FW_7002 = "e.ex.fw.7002";
    /** e.ex.fw.7003=Request body format error occurred. */
    public static final String E_EX_FW_7003 = "e.ex.fw.7003";
    /** e.ex.fw.7004=Unknown field exists in JSON. */
    public static final String E_EX_FW_7004 = "e.ex.fw.7004";
    /** e.ex.fw.7005=Type mismatch error occurred in JSON field. */
    public static final String E_EX_FW_7005 = "e.ex.fw.7005";
    /** e.ex.fw.7006=Type mismatch error occurred in request parameter or header or path variable. */
    public static final String E_EX_FW_7006 = "e.ex.fw.7006";
    /** e.ex.fw.8001=Business error occurred. */
    public static final String E_EX_FW_8001 = "e.ex.fw.8001";
    /** e.ex.fw.8002=Conflict with other processing occurred. */
    public static final String E_EX_FW_8002 = "e.ex.fw.8002";
    /** e.ex.fw.9001=System error occurred. */
    public static final String E_EX_FW_9001 = "e.ex.fw.9001";
    /** e.ex.fw.9002=System error occurred. */
    public static final String E_EX_FW_9002 = "e.ex.fw.9002";
    /** e.ex.fw.9003=System error occurred. */
    public static final String E_EX_FW_9003 = "e.ex.fw.9003";
    /** e.sl.fw.5001=対象データが見つかりません。 */
    public static final String E_SL_FW_5001 = "e.sl.fw.5001";
    /** e.sl.fw.5002= */
    public static final String E_SL_FW_5002 = "e.sl.fw.5002";
    /** e.sl.fw.5003= */
    public static final String E_SL_FW_5003 = "e.sl.fw.5003";
    /** e.sl.fw.5004= */
    public static final String E_SL_FW_5004 = "e.sl.fw.5004";
    /** e.sl.fw.5005= */
    public static final String E_SL_FW_5005 = "e.sl.fw.5005";
    /** e.sl.fw.5006= */
    public static final String E_SL_FW_5006 = "e.sl.fw.5006";
    /** e.sl.fw.5007= */
    public static final String E_SL_FW_5007 = "e.sl.fw.5007";
    /** e.sl.fw.5008= */
    public static final String E_SL_FW_5008 = "e.sl.fw.5008";
    /** e.sl.fw.5009= */
    public static final String E_SL_FW_5009 = "e.sl.fw.5009";
    /** e.sl.fw.5010= */
    public static final String E_SL_FW_5010 = "e.sl.fw.5010";
    /** e.sl.fw.6001=ファイルアップロードに失敗しました。 */
    public static final String E_SL_FW_6001 = "e.sl.fw.6001";
    /** e.sl.fw.6002= */
    public static final String E_SL_FW_6002 = "e.sl.fw.6002";
    /** e.sl.fw.6003= */
    public static final String E_SL_FW_6003 = "e.sl.fw.6003";
    /** e.sl.fw.6004= */
    public static final String E_SL_FW_6004 = "e.sl.fw.6004";
    /** e.sl.fw.6005= */
    public static final String E_SL_FW_6005 = "e.sl.fw.6005";
    /** e.sl.fw.6006= */
    public static final String E_SL_FW_6006 = "e.sl.fw.6006";
    /** e.sl.fw.6007= */
    public static final String E_SL_FW_6007 = "e.sl.fw.6007";
    /** e.sl.fw.6008= */
    public static final String E_SL_FW_6008 = "e.sl.fw.6008";
    /** e.sl.fw.6009= */
    public static final String E_SL_FW_6009 = "e.sl.fw.6009";
    /** e.sl.fw.6010= */
    public static final String E_SL_FW_6010 = "e.sl.fw.6010";
    /** e.sl.fw.7001=不正な画面遷移が発生しました。 */
    public static final String E_SL_FW_7001 = "e.sl.fw.7001";
    /** e.sl.fw.7002=不正な画面操作(CSRF)が発生しました。 */
    public static final String E_SL_FW_7002 = "e.sl.fw.7002";
    /** e.sl.fw.7003=このページにアクセスする権限がありません。 */
    public static final String E_SL_FW_7003 = "e.sl.fw.7003";
    /** e.sl.fw.7004=Missing CSRF detected! */
    public static final String E_SL_FW_7004 = "e.sl.fw.7004";
    /** e.sl.fw.7005=許可されていない文字が送信されました。 */
    public static final String E_SL_FW_7005 = "e.sl.fw.7005";
    /** e.sl.fw.7006= */
    public static final String E_SL_FW_7006 = "e.sl.fw.7006";
    /** e.sl.fw.7007= */
    public static final String E_SL_FW_7007 = "e.sl.fw.7007";
    /** e.sl.fw.7008= */
    public static final String E_SL_FW_7008 = "e.sl.fw.7008";
    /** e.sl.fw.7009= */
    public static final String E_SL_FW_7009 = "e.sl.fw.7009";
    /** e.sl.fw.7010= */
    public static final String E_SL_FW_7010 = "e.sl.fw.7010";
    /** e.sl.fw.8001=業務エラーが発生しました。 */
    public static final String E_SL_FW_8001 = "e.sl.fw.8001";
    /** e.sl.fw.9001=システムエラーが発生しました。 */
    public static final String E_SL_FW_9001 = "e.sl.fw.9001";
    /** e.sl.fw.9002=データベースアクセスに失敗しました。 */
    public static final String E_SL_FW_9002 = "e.sl.fw.9002";
    /** e.sl.pr.2001=URLの有効期間を過ぎています。 */
    public static final String E_SL_PR_2001 = "e.sl.pr.2001";
    /** e.sl.pr.5001=ユーザ名とトークンの組み合わせが一致しません。 */
    public static final String E_SL_PR_5001 = "e.sl.pr.5001";
    /** e.sl.pr.5002=無効なトークンです。 */
    public static final String E_SL_PR_5002 = "e.sl.pr.5002";
    /** e.sl.pr.5003=無効な暗証番号です。 */
    public static final String E_SL_PR_5003 = "e.sl.pr.5003";
    /** e.sl.pr.5004=試行回数の上限に達しました。 */
    public static final String E_SL_PR_5004 = "e.sl.pr.5004";
    /** e.sl.fa.5001=アカウントが見つかりません。 ユーザ名 : {0} */
    public static final String E_SL_FA_5001 = "e.sl.fa.5001";
    /** e.sl.ac.5001=そのユーザ名は既に使われています。 */
    public static final String E_SL_AC_5001 = "e.sl.ac.5001";
    /** i.sl.ac.0001=API KEYを設定しました。 */
    public static final String I_SL_AC_0001 = "i.sl.ac.0001";
    /** w.sl.pe.0001=パスワードの有効期限が切れたため、変更してください。 */
    public static final String W_SL_PE_0001 = "w.sl.pe.0001";
    /** e.sl.mc.5001=ユーザ名とトークンの組み合わせが一致しません。 */
    public static final String E_SL_MC_5001 = "e.sl.mc.5001";
    /** e.sl.mc.5002=無効なトークンです。 */
    public static final String E_SL_MC_5002 = "e.sl.mc.5002";
    /** e.sl.mc.5003=無効な暗証番号です。 */
    public static final String E_SL_MC_5003 = "e.sl.mc.5003";
    /** e.sl.mc.5004=暗証番号の有効期限が切れました。 */
    public static final String E_SL_MC_5004 = "e.sl.mc.5004";
    /** e.sl.mc.5005=試行回数の上限に達しました。 */
    public static final String E_SL_MC_5005 = "e.sl.mc.5005";
    /** title.welcome.home=welcome home */
    public static final String TITLE_WELCOME_HOME = "title.welcome.home";
    /** i.cm.fw.0001=登録しました。 */
    public static final String I_CM_FW_0001 = "i.cm.fw.0001";
    /** i.cm.fw.0002=状態を変更しました。 */
    public static final String I_CM_FW_0002 = "i.cm.fw.0002";
    /** i.cm.fw.0003=削除しました。 */
    public static final String I_CM_FW_0003 = "i.cm.fw.0003";
    /** i.cm.fw.0004=保存しました。 */
    public static final String I_CM_FW_0004 = "i.cm.fw.0004";
    /** i.cm.fw.0005=下書き保存しました。 */
    public static final String I_CM_FW_0005 = "i.cm.fw.0005";
    /** i.cm.fw.0006=下書きを取り消しました。 */
    public static final String I_CM_FW_0006 = "i.cm.fw.0006";
    /** i.cm.fw.0007= */
    public static final String I_CM_FW_0007 = "i.cm.fw.0007";
    /** i.cm.fw.0008=無効データは編集できません。そのため参照モードで開きました。 */
    public static final String I_CM_FW_0008 = "i.cm.fw.0008";
    /** i.cm.fw.0009=検索条件を指定してください。 */
    public static final String I_CM_FW_0009 = "i.cm.fw.0009";
    /** i.sl.va.0001=コードリストを更新しました。 */
    public static final String I_SL_VA_0001 = "i.sl.va.0001";
    /** w.cm.fw.2001=登録内容に変更はありません。 */
    public static final String W_CM_FW_2001 = "w.cm.fw.2001";
    /** w.cm.fw.2002=同じ値が既に登録されています。({0} = {1}) */
    public static final String W_CM_FW_2002 = "w.cm.fw.2002";
    /** w.cm.fw.2003=データの状態が有効でなければ無効化できません。下書きの場合は取り消してから無効化してください。 */
    public static final String W_CM_FW_2003 = "w.cm.fw.2003";
    /** w.cm.fw.2004=データの状態が無効でなければ無効解除できません。 */
    public static final String W_CM_FW_2004 = "w.cm.fw.2004";
    /** w.cm.fw.2005=データの状態が下書きでなければ下書き取消はできません。 */
    public static final String W_CM_FW_2005 = "w.cm.fw.2005";
    /** e.cm.fw.8001=楽観的排他制御により登録に失敗しました。画面を開き直して登録をやり直して下さい。 */
    public static final String E_CM_FW_8001 = "e.cm.fw.8001";
    /** e.cm.fw.8002=制約違反によりテーブル更新に失敗しました。({0}) */
    public static final String E_CM_FW_8002 = "e.cm.fw.8002";
    /** e.cm.fw.9001=登録に失敗しました。({0}) */
    public static final String E_CM_FW_9001 = "e.cm.fw.9001";
    /** typeMismatch="{0}" is invalid. */
    public static final String TYPEMISMATCH = "typeMismatch";
    /** typeMismatch.int="{0}" 整数で入力してください */
    public static final String TYPEMISMATCH_INT = "typeMismatch.int";
    /** typeMismatch.double="{0}" must be a double. */
    public static final String TYPEMISMATCH_DOUBLE = "typeMismatch.double";
    /** typeMismatch.float="{0}" must be a float. */
    public static final String TYPEMISMATCH_FLOAT = "typeMismatch.float";
    /** typeMismatch.long="{0}" must be a long. */
    public static final String TYPEMISMATCH_LONG = "typeMismatch.long";
    /** typeMismatch.short="{0}" must be a short. */
    public static final String TYPEMISMATCH_SHORT = "typeMismatch.short";
    /** typeMismatch.boolean="{0}" must be a boolean. */
    public static final String TYPEMISMATCH_BOOLEAN = "typeMismatch.boolean";
    /** typeMismatch.java.lang.Integer="{0}" 整数で入力してください */
    public static final String TYPEMISMATCH_JAVA_LANG_INTEGER = "typeMismatch.java.lang.Integer";
    /** typeMismatch.java.lang.Double="{0}" must be a double. */
    public static final String TYPEMISMATCH_JAVA_LANG_DOUBLE = "typeMismatch.java.lang.Double";
    /** typeMismatch.java.lang.Float="{0}" must be a float. */
    public static final String TYPEMISMATCH_JAVA_LANG_FLOAT = "typeMismatch.java.lang.Float";
    /** typeMismatch.java.lang.Long="{0}" must be a long. */
    public static final String TYPEMISMATCH_JAVA_LANG_LONG = "typeMismatch.java.lang.Long";
    /** typeMismatch.java.lang.Short="{0}" must be a short. */
    public static final String TYPEMISMATCH_JAVA_LANG_SHORT = "typeMismatch.java.lang.Short";
    /** typeMismatch.java.lang.Boolean="{0}" is not a boolean. */
    public static final String TYPEMISMATCH_JAVA_LANG_BOOLEAN = "typeMismatch.java.lang.Boolean";
    /** typeMismatch.java.util.Date="{0}" is not a date. */
    public static final String TYPEMISMATCH_JAVA_UTIL_DATE = "typeMismatch.java.util.Date";
    /** typeMismatch.java.lang.Enum="{0}" is not a valid value. */
    public static final String TYPEMISMATCH_JAVA_LANG_ENUM = "typeMismatch.java.lang.Enum";
    /** HISTORY_VIOLATION=Password matches one of %1$s previous passwords. */
    public static final String HISTORY_VIOLATION = "HISTORY_VIOLATION";
    /** ILLEGAL_WORD=Password contains the dictionary word '%1$s'. */
    public static final String ILLEGAL_WORD = "ILLEGAL_WORD";
    /** ILLEGAL_WORD_REVERSED=Password contains the reversed dictionary word '%1$s'. */
    public static final String ILLEGAL_WORD_REVERSED = "ILLEGAL_WORD_REVERSED";
    /** ILLEGAL_DIGEST_WORD=Password contains a dictionary word. */
    public static final String ILLEGAL_DIGEST_WORD = "ILLEGAL_DIGEST_WORD";
    /** ILLEGAL_DIGEST_WORD_REVERSED=Password contains a reversed dictionary word. */
    public static final String ILLEGAL_DIGEST_WORD_REVERSED = "ILLEGAL_DIGEST_WORD_REVERSED";
    /** ILLEGAL_MATCH=Password matches the illegal pattern '%1$s'. */
    public static final String ILLEGAL_MATCH = "ILLEGAL_MATCH";
    /** ALLOWED_MATCH=Password must match pattern '%1$s'. */
    public static final String ALLOWED_MATCH = "ALLOWED_MATCH";
    /** ILLEGAL_CHAR=Password %2$s the illegal character '%1$s'. */
    public static final String ILLEGAL_CHAR = "ILLEGAL_CHAR";
    /** ALLOWED_CHAR=Password %2$s the illegal character '%1$s'. */
    public static final String ALLOWED_CHAR = "ALLOWED_CHAR";
    /** ILLEGAL_QWERTY_SEQUENCE=Password contains the illegal QWERTY sequence '%1$s'. */
    public static final String ILLEGAL_QWERTY_SEQUENCE = "ILLEGAL_QWERTY_SEQUENCE";
    /** ILLEGAL_ALPHABETICAL_SEQUENCE=Password contains the illegal alphabetical sequence '%1$s'. */
    public static final String ILLEGAL_ALPHABETICAL_SEQUENCE = "ILLEGAL_ALPHABETICAL_SEQUENCE";
    /** ILLEGAL_NUMERICAL_SEQUENCE=Password contains the illegal numerical sequence '%1$s'. */
    public static final String ILLEGAL_NUMERICAL_SEQUENCE = "ILLEGAL_NUMERICAL_SEQUENCE";
    /** ILLEGAL_USERNAME=パスワードにユーザID'%1$s'を含めることができません. */
    public static final String ILLEGAL_USERNAME = "ILLEGAL_USERNAME";
    /** ILLEGAL_USERNAME_REVERSED=Password %2$s the user id '%1$s' in reverse. */
    public static final String ILLEGAL_USERNAME_REVERSED = "ILLEGAL_USERNAME_REVERSED";
    /** ILLEGAL_WHITESPACE=Password %2$s a whitespace character. */
    public static final String ILLEGAL_WHITESPACE = "ILLEGAL_WHITESPACE";
    /** ILLEGAL_NUMBER_RANGE=Password %2$s the number '%1$s'. */
    public static final String ILLEGAL_NUMBER_RANGE = "ILLEGAL_NUMBER_RANGE";
    /** ILLEGAL_REPEATED_CHARS=Password contains %3$s sequences of %1$s or more repeated characters, but only %2$s allowed: %4$s. */
    public static final String ILLEGAL_REPEATED_CHARS = "ILLEGAL_REPEATED_CHARS";
    /** INSUFFICIENT_UPPERCASE=パスワードは %1$s 文字以上の大文字が必要です. */
    public static final String INSUFFICIENT_UPPERCASE = "INSUFFICIENT_UPPERCASE";
    /** INSUFFICIENT_LOWERCASE=パスワードは %1$s 文字以上の小文字が必要です. */
    public static final String INSUFFICIENT_LOWERCASE = "INSUFFICIENT_LOWERCASE";
    /** INSUFFICIENT_ALPHABETICAL=パスワードは %1$s 文字以上のアルファベットが必要です. */
    public static final String INSUFFICIENT_ALPHABETICAL = "INSUFFICIENT_ALPHABETICAL";
    /** INSUFFICIENT_DIGIT=パスワードは %1$s 文字以上の数字が必要です. */
    public static final String INSUFFICIENT_DIGIT = "INSUFFICIENT_DIGIT";
    /** INSUFFICIENT_SPECIAL=パスワードは %1$s 文字以上の記号が必要です. */
    public static final String INSUFFICIENT_SPECIAL = "INSUFFICIENT_SPECIAL";
    /** INSUFFICIENT_CHARACTERISTICS=パスワードは、%3$s ルールのうち %1$s を満たしていますが、最低 %2$s ルールを満たす必要があります. */
    public static final String INSUFFICIENT_CHARACTERISTICS = "INSUFFICIENT_CHARACTERISTICS";
    /** INSUFFICIENT_COMPLEXITY=Password meets %2$s complexity rules, but %3$s are required. */
    public static final String INSUFFICIENT_COMPLEXITY = "INSUFFICIENT_COMPLEXITY";
    /** INSUFFICIENT_COMPLEXITY_RULES=No rules have been configured for a password of length %1$s. */
    public static final String INSUFFICIENT_COMPLEXITY_RULES = "INSUFFICIENT_COMPLEXITY_RULES";
    /** SOURCE_VIOLATION=Password cannot be the same as your %1$s password. */
    public static final String SOURCE_VIOLATION = "SOURCE_VIOLATION";
    /** TOO_LONG=Password must be no more than %2$s characters in length. */
    public static final String TOO_LONG = "TOO_LONG";
    /** TOO_SHORT=パスワードは %1$s 文字以上にしてください. */
    public static final String TOO_SHORT = "TOO_SHORT";
    /** TOO_MANY_OCCURRENCES=Password contains %2$s occurrences of the character '%1$s', but at most %3$s are allowed. */
    public static final String TOO_MANY_OCCURRENCES = "TOO_MANY_OCCURRENCES";
    /** javax.validation.constraints.NotNull.message=入力してください */
    public static final String JAVAX_VALIDATION_CONSTRAINTS_NOTNULL_MESSAGE = "javax.validation.constraints.NotNull.message";
    /** jp.co.stnet.cms.sales.domain.validation.ValidService.message=入力してください */
    public static final String JP_CO_STNET_CMS_SALES_DOMAIN_VALIDATION_VALIDSERVICE_MESSAGE = "jp.co.stnet.cms.sales.domain.validation.ValidService.message";
    /** jp.co.stnet.cms.sales.domain.validation.FileFormRequired.message=ファイルを添付してください */
    public static final String JP_CO_STNET_CMS_SALES_DOMAIN_VALIDATION_FILEFORMREQUIRED_MESSAGE = "jp.co.stnet.cms.sales.domain.validation.FileFormRequired.message";
    /** jp.co.stnet.cms.sales.domain.validation.DocumentCsvBeanDocCategory2.message=登録されていない区分１と区分２の組み合わせです */
    public static final String JP_CO_STNET_CMS_SALES_DOMAIN_VALIDATION_DOCUMENTCSVBEANDOCCATEGORY2_MESSAGE = "jp.co.stnet.cms.sales.domain.validation.DocumentCsvBeanDocCategory2.message";
    /** e.validation.fw.8001=このコードは既に登録されています */
    public static final String E_VALIDATION_FW_8001 = "e.validation.fw.8001";
    /** com.example.app.common.validation.NotReusedPassword.message=現在のパスワードは使えません */
    public static final String COM_EXAMPLE_APP_COMMON_VALIDATION_NOTREUSEDPASSWORD_MESSAGE = "com.example.app.common.validation.NotReusedPassword.message";
}
